CREATE TABLE IF NOT EXISTS field (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR (255) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS math_figure (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR (255) NOT NULL,
	description TEXT,
	url VARCHAR (255),
	field_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (field_id) REFERENCES field(id) 
);

CREATE TABLE IF NOT EXISTS dbrole (
	id INTEGER AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	auth TEXT NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dbuser (
	id INTEGER AUTO_INCREMENT NOT NULL,
	username VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	role_id Integer NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (role_id) REFERENCES dbrole (id)
);